version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
    interval: "daily"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "automerge"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "automerge"
