version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1-5"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "automerge"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1-5"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "automerge"
